import path from "node:path";
import type { Project } from "./project.js";

export const generatedHeader =
  "// Generated by RevisionLab. This file belongs to your project.\n";

function configImport(from: string): string {
  const relative = path.posix.relative(
    path.posix.dirname(from),
    "revisionlab.config",
  );
  return relative.startsWith(".") ? relative : `./${relative}`;
}

export function integrationFiles(
  project: Project,
  projectId: string,
  protect: boolean,
): Record<string, string> {
  const extension = project.typescript ? "ts" : "js";
  const jsxExtension = project.typescript ? "tsx" : "jsx";
  const app = project.app.replaceAll(path.sep, "/");
  const route = `${app}/api/revisionlab/[...path]/route.${extension}`;
  const files: Record<string, string> = {
    [`revisionlab.config.${extension}`]: `${generatedHeader}import { defineRevisionLabConfig } from "revisionlab/server";

export default defineRevisionLabConfig({
  projectId: ${JSON.stringify(projectId)},
  projectName: ${JSON.stringify(project.name)},
  // Database, owner email, and delivery settings are read from environment variables.
});
`,
    [`${app}/revisionlab/page.${jsxExtension}`]: `${generatedHeader}import { RevisionLabWorkspace } from "revisionlab";

export default function RevisionLabPage() {
  return <RevisionLabWorkspace />;
}
`,
    [`${app}/revisionlab/access/page.${jsxExtension}`]: `${generatedHeader}import { RevisionLabAccess } from "revisionlab";

export default function RevisionLabAccessPage() {
  return <RevisionLabAccess />;
}
`,
    [route]: `${generatedHeader}import { createRevisionLabHandler } from "revisionlab/server";
import config from ${JSON.stringify(configImport(route))};

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const handler = createRevisionLabHandler(config);
export { handler as GET, handler as POST, handler as PATCH, handler as DELETE };
`,
    ".revisionlab/.gitignore":
      "# Local runtime data and backups must not be committed.\n*\n!.gitignore\n!installation.json\n",
    ".revisionlab.env.example": `# Local development needs no environment variables.
# Copy these settings into .env.local for a persistent shared deployment.
REVISIONLAB_DATABASE_URL=
REVISIONLAB_DATABASE_AUTH_TOKEN=
REVISIONLAB_OWNER_EMAIL=
RESEND_API_KEY=
REVISIONLAB_EMAIL_FROM=
`,
  };
  if (protect) {
    const filename = `${app === "src/app" ? "src/" : ""}${project.nextMajor >= 16 ? "proxy" : "middleware"}.${extension}`;
    const functionName = project.nextMajor >= 16 ? "proxy" : "middleware";
    files[filename] =
      `${generatedHeader}import { NextResponse } from "next/server";
${project.typescript ? 'import type { NextRequest } from "next/server";\n' : ""}import { protectRevisionLab } from "revisionlab/server";
import revisionlabConfig from ${JSON.stringify(configImport(filename))};

export async function ${functionName}(request${project.typescript ? ": NextRequest" : ""}) {
  return (await protectRevisionLab(request, revisionlabConfig)) ?? NextResponse.next();
}

export const config = {
${project.nextMajor < 16 ? '  runtime: "nodejs",\n' : ""}  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
};
`;
  }
  return files;
}
