import type { DesignSystem } from "./types.js";

// Resource URLs supplied by the product owner; star counts are dated GitHub API snapshots.
export const designSystems: DesignSystem[] = [
  {
    id: "govuk-react",
    name: "GOV.UK React",
    docsUrl: "https://govuk-react.github.io/govuk-react/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/govuk-react/govuk-react",
    stars: 458,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "govuk-chakra",
    name: "GOV.UK Chakra",
    docsUrl: "https://gov-uk-gds-react-chakra.vercel.app/",
    designUrl: "https://github.com/gil00pita/govuk-chakra/blob/main/DESIGN.md",
    skillUrl: "https://github.com/gil00pita/govuk-chakra/blob/main/SKILL.md",
    mcpUrl: "",
    githubUrl: "https://github.com/gil00pita/govuk-chakra",
    stars: 0,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "mui",
    name: "MUI / Material UI",
    docsUrl: "https://mui.com/material-ui/",
    designUrl: "",
    skillUrl: "https://github.com/mui/material-ui/tree/master/skills",
    mcpUrl: "https://mui.com/material-ui/getting-started/mcp/",
    githubUrl: "https://github.com/mui/material-ui",
    stars: 99123,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "ant-design",
    name: "Ant Design",
    docsUrl: "https://ant.design/components/overview/",
    designUrl: "https://ant.design/design.md",
    skillUrl:
      "https://github.com/ant-design/ant-design-cli/blob/main/skills/antd/SKILL.md",
    mcpUrl: "https://ant.design/docs/react/mcp/",
    githubUrl: "https://github.com/ant-design/ant-design",
    stars: 99654,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    docsUrl: "https://ui.shadcn.com/docs",
    designUrl: "",
    skillUrl:
      "https://github.com/shadcn-ui/ui/blob/main/skills/shadcn/SKILL.md",
    mcpUrl: "https://ui.shadcn.com/docs/mcp",
    githubUrl: "https://github.com/shadcn-ui/ui",
    stars: 124987,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "react-bootstrap",
    name: "React Bootstrap",
    docsUrl: "https://react-bootstrap.github.io/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/react-bootstrap/react-bootstrap",
    stars: 22601,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "chakra",
    name: "Chakra UI",
    docsUrl: "https://chakra-ui.com/docs",
    designUrl: "",
    skillUrl:
      "https://github.com/chakra-ui/chakra-ui/blob/main/skills/chakra-ui-builder/SKILL.md",
    mcpUrl: "https://chakra-ui.com/docs/get-started/ai/mcp-server",
    githubUrl: "https://github.com/chakra-ui/chakra-ui",
    stars: 40674,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "radix",
    name: "Radix UI Primitives",
    docsUrl: "https://www.radix-ui.com/primitives/docs/overview/introduction",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/radix-ui/primitives",
    stars: 19360,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "headless",
    name: "Headless UI",
    docsUrl: "https://headlessui.com/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/tailwindlabs/headlessui",
    stars: 28768,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "mantine",
    name: "Mantine",
    docsUrl: "https://mantine.dev/",
    designUrl: "",
    skillUrl: "https://github.com/mantinedev/skills",
    mcpUrl: "https://mantine.dev/mcp/",
    githubUrl: "https://github.com/mantinedev/mantine",
    stars: 31794,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "fluent",
    name: "Fluent UI React",
    docsUrl: "https://react.fluentui.dev/",
    designUrl: "",
    skillUrl:
      "https://github.com/microsoft/fluentui/blob/master/.agents/skills/v9-component/SKILL.md",
    mcpUrl: "",
    githubUrl: "https://github.com/microsoft/fluentui",
    stars: 20303,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "primereact",
    name: "PrimeReact",
    docsUrl: "https://primereact.dev/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/primefaces/primereact",
    stars: 8309,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "heroui",
    name: "HeroUI",
    docsUrl: "https://heroui.com/en/docs/react/getting-started/installation",
    designUrl: "",
    skillUrl:
      "https://github.com/heroui-inc/heroui/blob/v3/skills/heroui-react/SKILL.md",
    mcpUrl: "https://heroui.com/en/docs/react/getting-started/mcp-server",
    githubUrl: "https://github.com/heroui-inc/heroui",
    stars: 30850,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "spectrum",
    name: "React Spectrum",
    docsUrl: "https://react-spectrum.adobe.com/",
    designUrl: "",
    skillUrl:
      "https://react-spectrum.adobe.com/.well-known/skills/react-spectrum-s2/SKILL.md",
    mcpUrl:
      "https://github.com/adobe/react-spectrum/blob/main/packages/dev/mcp/s2/README.md",
    githubUrl: "https://github.com/adobe/react-spectrum",
    stars: 15906,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "carbon",
    name: "Carbon React",
    docsUrl:
      "https://www.carbondesignsystem.com/getting-started/developing/carbon-core/react",
    designUrl: "",
    skillUrl:
      "https://github.com/carbon-design-system/carbon-mcp/blob/main/public/skills/carbon-builder/SKILL.md",
    mcpUrl: "https://mcp.carbondesignsystem.com/mcp",
    githubUrl: "https://github.com/carbon-design-system/carbon",
    stars: 9514,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "blueprint",
    name: "Blueprint",
    docsUrl: "https://blueprintjs.com/docs/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/palantir/blueprint",
    stars: 22114,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "semantic",
    name: "Semantic UI React",
    docsUrl: "https://react.semantic-ui.com/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/Semantic-Org/Semantic-UI-React",
    stars: 13198,
    starsCheckedAt: "2026-10-02",
  },
  {
    id: "baseweb",
    name: "Base Web",
    docsUrl: "https://baseweb.design/",
    designUrl: "",
    skillUrl: "",
    mcpUrl: "",
    githubUrl: "https://github.com/uber/baseweb",
    stars: 9009,
    starsCheckedAt: "2026-10-02",
  },
];
