import type { Project, Prototype, RecordedStep } from "./types";

export const projects: Project[] = [
  {
    id: "commerce-platform",
    name: "Commerce platform",
    description: "Checkout, billing, and account-service prototypes for the commerce programme.",
    repository: "github.com/revisionlab-demo/commerce-platform",
    branch: "main",
    provider: "GitHub",
    role: "Owner",
    members: ["JD", "MP", "AK", "+2"],
    prototypeIds: ["checkout-service", "profile-settings", "billing-portal"],
    environmentVariables: [
      { id: "env-commerce-1", key: "PREVIEW_API_URL", secret: false, phase: "runtime", target: "both" },
      { id: "env-commerce-2", key: "SESSION_SIGNING_KEY", secret: true, phase: "runtime", target: "preview" },
    ],
    buildState: "ready",
    lastBuild: "4 minutes ago",
  },
  {
    id: "identity-programme",
    name: "Identity programme",
    description: "Account creation and verified first-run journeys.",
    repository: "github.com/revisionlab-demo/identity-prototypes",
    branch: "develop",
    provider: "GitHub",
    role: "Manager",
    members: ["MP", "NT", "+3"],
    prototypeIds: ["account-onboarding"],
    environmentVariables: [],
    buildState: "ready",
    lastBuild: "Yesterday",
  },
  {
    id: "support-experience",
    name: "Support experience",
    description: "Help-centre discovery and assisted contact routes.",
    repository: "github.com/revisionlab-demo/support-experience",
    branch: "main",
    provider: "GitHub",
    role: "Manager",
    members: ["SL", "NT"],
    prototypeIds: ["help-centre"],
    environmentVariables: [
      { id: "env-support-1", key: "SEARCH_INDEX", secret: false, phase: "build", target: "preview" },
    ],
    buildState: "attention",
    lastBuild: "19 Aug",
  },
];

export const prototypes: Prototype[] = [
  {
    id: "checkout-service",
    projectId: "commerce-platform",
    name: "Checkout service",
    description: "Responsive purchase journey for the next checkout release.",
    rootDirectory: "apps/checkout",
    framework: "Next.js",
    runtime: { installCommand: "pnpm install --frozen-lockfile", buildCommand: "pnpm build", startCommand: "pnpm start", port: 3000, healthPath: "/" },
    environmentVariables: [
      { id: "env-checkout-1", key: "CHECKOUT_EXPERIMENT_KEY", secret: true, phase: "runtime", target: "preview" },
    ],
    buildState: "ready",
    screenNames: ["Basket", "Delivery", "Payment", "Confirmation"],
    screens: 4,
    flows: 3,
    version: "v0.8.4",
    updated: "4 minutes ago",
    role: "Owner",
    privacy: "Private",
    replay: "healthy",
    members: ["JD", "MP", "AK", "+2"],
  },
  {
    id: "account-onboarding",
    projectId: "identity-programme",
    name: "Account onboarding",
    description: "Verified signup and first-run setup.",
    rootDirectory: "apps/onboarding",
    framework: "Angular",
    runtime: { installCommand: "npm ci", buildCommand: "npm run build", startCommand: "npm run start -- --host 0.0.0.0", port: 4200, healthPath: "/" },
    environmentVariables: [],
    buildState: "ready",
    screenNames: ["Welcome", "Account", "Verify", "Profile", "Preferences", "Ready"],
    screens: 6,
    flows: 2,
    version: "v1.2.0",
    updated: "Yesterday",
    role: "Manager",
    privacy: "Private",
    replay: "healthy",
    members: ["MP", "NT", "+3"],
  },
  {
    id: "profile-settings",
    projectId: "commerce-platform",
    name: "Profile settings",
    description: "Account, password, and session controls.",
    rootDirectory: "apps/profile",
    framework: "React + Vite",
    runtime: { installCommand: "pnpm install --frozen-lockfile", buildCommand: "pnpm build", startCommand: "pnpm preview --host 0.0.0.0", port: 4173, healthPath: "/" },
    environmentVariables: [],
    buildState: "ready",
    screenNames: ["Profile", "Password", "Sessions", "Complete"],
    screens: 4,
    flows: 2,
    version: "v0.6.1",
    updated: "2 days ago",
    role: "Owner",
    privacy: "Private",
    replay: "healthy",
    members: ["JD", "SL"],
  },
  {
    id: "billing-portal",
    projectId: "commerce-platform",
    name: "Billing portal",
    description: "Subscription and invoice management.",
    rootDirectory: "apps/billing",
    framework: "Vue",
    runtime: { installCommand: "pnpm install --frozen-lockfile", buildCommand: "pnpm build", startCommand: "pnpm preview --host 0.0.0.0", port: 4173, healthPath: "/" },
    environmentVariables: [],
    buildState: "ready",
    screenNames: ["Plan", "Invoices", "Payment method", "Confirm", "Receipt"],
    screens: 5,
    flows: 4,
    version: "v1.0.3",
    updated: "3 days ago",
    role: "Viewer",
    privacy: "Private",
    replay: "attention",
    members: ["AK", "RP", "+1"],
  },
  {
    id: "help-centre",
    projectId: "support-experience",
    name: "Help centre",
    description: "Support discovery and contact routes.",
    rootDirectory: ".",
    framework: "Astro",
    runtime: { installCommand: "pnpm install --frozen-lockfile", buildCommand: "pnpm build", startCommand: "pnpm preview --host 0.0.0.0", port: 4321, healthPath: "/" },
    environmentVariables: [],
    buildState: "attention",
    screenNames: ["Help home", "Article", "Contact"],
    screens: 3,
    flows: 1,
    version: "v0.4.7",
    updated: "19 Aug",
    role: "Manager",
    privacy: "Private",
    replay: "not-run",
    members: ["SL", "NT"],
  },
];

export const activity = [
  { action: "Replay completed", detail: "Checkout happy path · desktop", time: "4 min", actor: "Jamie Diaz", tone: "healthy" },
  { action: "Version published", detail: "v0.8.4 · 4 viewport snapshots", time: "12 min", actor: "Morgan Price", tone: "neutral" },
  { action: "Screen updated", detail: "Payment · stable targets checked", time: "2 hr", actor: "Jamie Diaz", tone: "neutral" },
  { action: "Access changed", detail: "Viewer invitation accepted", time: "1 day", actor: "Ari Khan", tone: "neutral" },
];

export const seedSteps: RecordedStep[] = [
  { id: "step-1", order: 1, from: "Basket", to: "Delivery", label: "Continue to delivery", flowId: "continue-to-delivery" },
  { id: "step-2", order: 2, from: "Delivery", to: "Payment", label: "Confirm delivery address", flowId: "confirm-address" },
  { id: "step-3", order: 3, from: "Payment", to: "Confirmation", label: "Pay securely", flowId: "pay-now" },
];

export const versionHistory = [
  { version: "v0.8.4", title: "Payment reassurance and review", note: "Clarified the final payment action and strengthened the error state.", author: "Jamie Diaz", time: "Today, 10:24", commit: "a18fd93", status: "Current", screens: 12 },
  { version: "v0.8.3", title: "Delivery address refinement", note: "Reduced repeated copy and added postcode lookup recovery.", author: "Morgan Price", time: "Yesterday, 16:42", commit: "fe84c01", status: "Available", screens: 12 },
  { version: "v0.8.2", title: "Responsive basket baseline", note: "Captured the first stable phone, tablet, and desktop evidence.", author: "Jamie Diaz", time: "2 Sep, 09:18", commit: "706bc4e", status: "Available", screens: 9 },
];
